[package]
name = "lish"
version = "0.1.0"
authors = ["Lee Keitel <lee@keitel.xyz>"]
edition = "2018"

[dependencies]
termion = "1.5"
path-absolutize = "1.1.3"
lazuli_vm = { git = "https://github.com/lfkeitel/lazuli-lisp" }
